# Day 3 — NumPy Fundamentals

## Objectives
- Create and inspect NumPy arrays.
- Practice indexing and slicing.
- Use boolean masking.
- Apply vectorized operations.
- Understand broadcasting.

In [2]:
import numpy as np
print ("Numpy version: ", np.__version__)

Numpy version:  2.3.5


In [3]:
numbers = np.array([10, 20, 30, 40, 50])
print(numbers)
print(type(numbers))

[10 20 30 40 50]
<class 'numpy.ndarray'>


## 2. Creating NumPy Arrays

NumPy provides several functions for creating arrays depending on the required data.

In [6]:
array_from_list = np.array([1, 2, 3, 4, 5])
zeros_array = np.zeros(5)
ones_array = np.ones((2,3))
range_array = np.arange(0, 10, 2)
linear_array = np.linspace (0, 1, 5)

print("From list:", array_from_list)
print("Zeros:" ,zeros_array)
print("Ones:" ,ones_array)
print("Using range:" ,range_array)
print("Using linspace:" ,linear_array)

From list: [1 2 3 4 5]
Zeros: [0. 0. 0. 0. 0.]
Ones: [[1. 1. 1.]
 [1. 1. 1.]]
Using range: [0 2 4 6 8]
Using linspace: [0.   0.25 0.5  0.75 1.  ]


In [8]:
sample_array = np.array([[10, 20, 30],[40, 50, 60]])

print("Array:\n", sample_array)
print("Shape\n", sample_array.shape)
print("Dimensions", sample_array.ndim)
print("Data type", sample_array.dtype)
print("Total elements", sample_array.size)

Array:
 [[10 20 30]
 [40 50 60]]
Shape
 (2, 3)
Dimensions 2
Data type int64
Total elements 6


## 3. Indexing and Slicing

NumPy indexing selects individual elements, while slicing selects a range of elements.

In [9]:
numbers = np.array([10,20,30,40,50])
print("first element:", numbers[0])
print("second element:", numbers[1])
print("last element:", numbers[-1])

first element: 10
second element: 20
last element: 50


In [10]:
print("First three elements:", numbers[:3])
print("Elements from index 1 to 3:", numbers [1:4])
print("Every second element:", numbers [::2])
print("Reversed array:", numbers [::-1])

First three elements: [10 20 30]
Elements from index 1 to 3: [20 30 40]
Every second element: [10 30 50]
Reversed array: [50 40 30 20 10]


In [12]:
matrix = np.array([
    [1,2,3],
    [4,5,6]
])

print("Matrix:\n", matrix)
print("Element at row 0,column 2", matrix [0,2])
print("Second column:", matrix [:,2])
print("Last row:", matrix [1,:])

Matrix:
 [[1 2 3]
 [4 5 6]]
Element at row 0,column 2 3
Second column: [3 6]
Last row: [4 5 6]


## 4. Vectorized Operations

Vectorized operations apply calculations to an entire NumPy array without using an explicit Python loop.

In [14]:
a = np.array([1, 2, 3, 4])

print("Original array", a)
print("Multiply by 2:", a * 2)
print("Add array to itself:", a+a)
print("Mean:", a.mean())

Original array [1 2 3 4]
Multiply by 2: [2 4 6 8]
Add array to itself: [2 4 6 8]
Mean: 2.5


## 5. Boolean Masking

Boolean masking selects array values that satisfy a condition.

In [15]:
a = np.array([1,2,3,4])

print("Original array:", a)
print("Condition:", a>2)
print("Values greater than 2:" , a[a>2])

Original array: [1 2 3 4]
Condition: [False False  True  True]
Values greater than 2: [3 4]


## 6. Broadcasting

Broadcasting allows NumPy to combine arrays with different but compatible shapes.

In [16]:
matrix = np.array([
    [1,2,3],
    [4,5,6]
])

row = np.array([10,20,30])

print(matrix + row)

[[11 22 33]
 [14 25 36]]


# NumPy Array Manipulation Lab

In [18]:
array_4x4 = np.arange (1,17).reshape(4,4)

print("Array:\n", array_4x4)
print("Shape:", array_4x4.shape)
print("Data type:", array_4x4.dtype)

Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Shape: (4, 4)
Data type: int64


In [19]:
second_column = array_4x4[:,1]
last_row = array_4x4[-1,:]

print("Second column:", second_column)
print("Last row", last_row)

Second column: [ 2  6 10 14]
Last row [13 14 15 16]


In [20]:
array_mean = array_4x4.mean()
values_above_mean = array_4x4[array_4x4 > array_mean]

print("Mean:", array_mean)
print("Values greater than the mean:", values_above_mean)

Mean: 8.5
Values greater than the mean: [ 9 10 11 12 13 14 15 16]


In [22]:
row = np.array([10, 20, 30, 40])
broadcast_result = array_4x4 + row

print("Row array:", row)
print("Broadcast result:\n", broadcast_result)

Row array: [10 20 30 40]
Broadcast result:
 [[11 22 33 44]
 [15 26 37 48]
 [19 30 41 52]
 [23 34 45 56]]
