# Week 2 - Day 3
# Linear Algebra for Machine Learning

## Why Linear Algebra Is the Language of Machine Learning

Every dataset in Machine Learning is represented as a matrix.

- Rows represent samples.
- Columns represent features.

Machine Learning models store their parameters as vectors or matrices, and training consists of mathematical operations on these objects.

Understanding vectors, matrices, dot products, and matrix multiplication is essential because these are the core operations behind every ML model.

import numpy as np

## Vectors

A vector is an ordered collection of numbers.

In Machine Learning, one data sample is represented as a vector.

Each value inside the vector is called a feature.

In [3]:
student = np.array([22, 3.8])

print(student)

[22.   3.8]


In [4]:
house = np.array([180, 4, 250000])

print(house)

[   180      4 250000]


## Vector Shape

The shape tells us how many elements the vector contains.

In [6]:
print(student.shape)
print(house.shape)

(2,)
(3,)


## Matrices

A matrix is a collection of vectors.

Rows represent samples.

Columns represent features.

In [7]:
students = np.array([
    [22, 3.8],
    [20, 3.5],
    [25, 3.9],
    [21, 3.2]
])

print(students)

[[22.   3.8]
 [20.   3.5]
 [25.   3.9]
 [21.   3.2]]


## Matrix Shape

Matrix shape is written as:

(rows, columns)

In [8]:
print(students.shape)

(4, 2)


## Accessing Matrix Elements

In [9]:
print(students[0])

print(students[:,0])

print(students[:,1])

[22.   3.8]
[22. 20. 25. 21.]
[3.8 3.5 3.9 3.2]


## Dot Product

The dot product combines two vectors into a single number.

Machine Learning models use the dot product to calculate predictions.

In [10]:
x = np.array([2, 4])

w = np.array([3, 5])

result = np.dot(x, w)

print(result)

26


In [11]:
scores = np.array([80, 90, 100])

weights = np.array([0.2, 0.3, 0.5])

prediction = np.dot(scores, weights)

print(prediction)

93.0


## Matrix Multiplication

Matrices can be multiplied only when their dimensions are compatible.

(number of columns in the first matrix)

must equal

(number of rows in the second matrix)

In [12]:
A = np.array([
    [1,2],
    [3,4]
])

B = np.array([
    [5,6],
    [7,8]
])

C = np.matmul(A,B)

print(C)

[[19 22]
 [43 50]]


In [13]:
print(A.shape)

print(B.shape)

print(C.shape)

(2, 2)
(2, 2)
(2, 2)


In [14]:
person = np.array([25, 180, 75])

print(person)

[ 25 180  75]


In [15]:
people = np.array([
    [25,180,75],
    [30,175,80],
    [22,170,65]
])

print(people)

[[ 25 180  75]
 [ 30 175  80]
 [ 22 170  65]]


In [16]:
x = np.array([1,2,3])

w = np.array([4,5,6])

print(np.dot(x,w))

32


In [17]:
A = np.array([
    [1,2],
    [3,4]
])

B = np.array([
    [2],
    [5]
])

C = np.matmul(A,B)

print(C)

print(C.shape)

[[12]
 [26]]
(2, 1)
